---
title: "Prepare loom file for scvelo"
author: "Guillaume Harmange"
date: "1/27/2021"
output: html_document
---


Load Pakages
```{r}
library(Seurat)
library(SeuratDisk)
library(SeuratWrappers)
```
Make loom file into a seurat object
```{r}
#Change files paths to correct path
ldat <- ReadVelocity(file = "/Users/guillaumeharmange/Desktop/20201110_10x2_WM983B_NoDrug_seq1/10X2_seq1_NoDrugWM983B_count/velocyto/10X2_seq1_NoDrugWM983B_count.loom")
vlo<-as.Seurat(ldat)
vlo[["RNA"]] <- vlo[["spliced"]]
```
Now apply what ever processing you want to the data (this is just a rondom example I used for my data)
```{r}
#mitochondrial and ribosomal percent in each cell
vlo[["percent.mt"]] <- PercentageFeatureSet(object = vlo, pattern = "^MT-")

#filter cells
vlo <- subset(x = vlo, subset = nFeature_RNA > 4000 & nFeature_RNA < 10000 & percent.mt < 25)

# transform data removing variability cause by mitochondrail genes
vlo<-SCTransform(vlo, vars.to.regress = c("percent.mt"))

#Add cell cycle information
s.genes <- cc.genes$s.genes
g2m.genes <- cc.genes$g2m.genes
vlo <- CellCycleScoring(vlo, s.features = s.genes, g2m.features = g2m.genes, set.ident = TRUE)

#run PCA
vlo <- RunPCA(object = vlo)

#Run UMAP
vlo <- FindNeighbors(object = vlo, dims = c(1:20))
vlo <- FindClusters(object = vlo, resolution = .5)
vlo <- RunUMAP(object = vlo, dims = 1:20)
#visualize UMAP
DimPlot(object = vlo, reduction = 'umap', pt.size = 2, label = TRUE)
```
Export processed data
```{r}
DefaultAssay(vlo) <- "RNA"
#put this file in velocyto output folder with this name  (or you need to change stuff in python script)
SaveH5Seurat(vlo, filename = "/Users/guillaumeharmange/Desktop/20201110_10x2_WM983B_NoDrug_seq1/10X2_seq1_NoDrugWM983B_count/velocyto/SeuratProcessed.h5Seurat")
#this path is just the path inputed above
Convert("/Users/guillaumeharmange/Desktop/20201110_10x2_WM983B_NoDrug_seq1/10X2_seq1_NoDrugWM983B_count/velocyto/SeuratProcessed.h5Seurat", dest = "h5ad")
```
